hpc-maths/ponio

solver/include/solver/generic_butcher_rk.hpp, solver/include/solver/ponio_config.hpp, solver/template/tpl_butcher_methods.hxx
Forget to add a tolerance to Lawson methods
=> add Adaptive time step methods for Lawson Runge-Kutta methods

solver/include/solver/observer.hpp, solver/test/main.cpp, solver/test/observer.hxx
=> fix file_observer

solver/demos/CMakeLists.txt, solver/demos/curtiss_hirschfelder.cpp, solver/demos/curtiss_hirschfelder.py, solver/include/solver/solver.hpp
=> Loop controler

.github/workflows/midnight.yml, solver/demos/brownian.cpp, solver/include/solver/eigen_linear_algebra.hpp, solver/include/solver/splitting/detail.hpp, solver/include/solver/splitting/strang.hpp
Fix the clang-tidy launch command line
=> Fix clang tidy

conanfile.txt, environment/conda-environment-test.yml, environment/conda-environment.yml, solver/demos/CMakeLists.txt, solver/demos/brownian.cpp, solver/demos/lotka_volterra.cpp, solver/include/solver/runge_kutta.hpp, solver/include/solver/solver.hpp, solver/include/solver/splitting.hpp
This time it is a fix of all clang-tidy warnings
=> Fix clang tidy warnings

solver/demos/heat_rock.cpp, solver/include/solver/runge_kutta/rock.hpp
=> Improve ROCK UI

.github/workflows/linux.yml, environment/conda-environment-test.yml, solver/demos/heat_samurai.cpp, solver/include/solver/linear_algebra.hpp, solver/include/solver/problem.hpp, solver/include/solver/runge_kutta/dirk.hpp, solver/include/solver/samurai_linear_algebra.hpp
Rewrite a part of DIRK methods to add possibility to define problem as samurai operators
=> Change DIRK method for samurai

solver/demos/heat_rock.cpp, solver/demos/heat_samurai.cpp, solver/include/solver/linear_algebra.hpp, solver/include/solver/runge_kutta/exprk.hpp, solver/include/solver/runge_kutta/rock.hpp
Fix clang-tidy warnings.
By submitting this PR, you agree to follow our [Code of Conduct](https://github.com/hpc-maths/ponio/blob/master/solver/doc/CODE_OF_CONDUCT.md)
=> fix: clang-tidy fix

.github/workflows/ponio-ci.yml, pixi.toml, ponio/include/ponio/runge_kutta/pirock.hpp, ponio/include/ponio/runge_kutta/rock.hpp, ponio/include/ponio/samurai_linear_algebra.hpp
Fix Shampine's trick with samurai
Fix ROCK with samurai (you can't move a field!)
=> fix: Shampine's trick with samurai

.github/workflows/midnight.yml
Change version of pixi in midnight.yml CI file
Midnight CI fails due to pixi version update.
=> fix: fix midnight CI

.cppcheck, ponio/doc/source/api/method.rst, ponio/doc/source/api/splitting.rst, ponio/doc/source/user/lorenz.rst, ponio/examples/lorenz_all.cpp, ponio/include/ponio/detail.hpp, ponio/include/ponio/method.hpp, ponio/include/ponio/splitting.hpp, ponio/include/ponio/splitting/detail.hpp, ponio/include/ponio/splitting/lie.hpp, ponio/include/ponio/splitting/strang.hpp
Add an adaptive time step technique for Strang splitting coming from [Adaptive time splitting method for multi-scale evolutionary partial differential equations, Descombes S. & Duarte M. & Dumont T. & Louvet V. & Massot M. (2011) *Confluentes Mathematici*](https://doi.org/10.1142/S1793744211000412)
* lorenz_all.cpp
=> feat: adaptive time step for Strang splitting method

.github/workflows/release-please.yml
Update version of release-please
=> fix: change version of release-please and add token

README.md, analysis/analysis.py, ponio/doc/source/conf.py, ponio/template/tpl_butcher_methods.hxx, ponio/template/tpl_doc_algorithms.rst
=> docs: fix url in documentation

ponio/include/ponio/runge_kutta/pirock.hpp, ponio/include/ponio/runge_kutta/rock.hpp
Fix expressions of computation of error estimation and factor to change time step.
Adaptive time method based on ROCK4 gives very small time steps.
Comparison between results of ROCK4 in reference Fortran code and ponio code.
=> fix: embedded ROCK4

ponio/include/ponio/runge_kutta/rkl.hpp
=> docs: fix documentation of RKL

.cppcheck, ponio/doc/source/api/solver.rst, ponio/examples/CMakeLists.txt, ponio/examples/belousov_zhabotinsky_pirock.cpp, ponio/examples/brusselator_advection_2d.cpp, ponio/examples/brusselator_advection_2d.py, ponio/examples/heat_rock.cpp, ponio/examples/heat_samurai.cpp, ponio/examples/heat_samurai.py, ponio/examples/nagumo_pirock.cpp, ponio/examples/nagumo_pirock.py, ponio/include/ponio/iteration_info.hpp, ponio/include/ponio/splitting/strang.hpp, ponio/include/ponio/user_defined_method.hpp, ponio/test/iteration_info.hxx
Change access to delta parameter for `ponio::splitting::adaptive_strang` into `ponio::iteration_info`
=> style: improve API for adaptive Strang splitting method (delta parameter)

CMakeLists.txt, ponio/doc/scripts/pre_install.sh
Change default build to offline (no request for doi).
=> feat: change default build to -DBUILD_OFFLINE

ponio/doc/source/index.rst, ponio/examples/nagumo_pirock.py, ponio/include/ponio/iteration_info.hpp, ponio/include/ponio/runge_kutta/pirock.hpp, ponio/template/tpl_doc_algorithms.rst
Use the same formula to compute error as the Fortran code of PIROCK method.
=> feat: improve PIROCK adaptive time step method

.github/workflows/pages.yml
Upgrade pixi setup and version.
=> fix: fix pixi version for pages

.github/workflows/midnight.yml, pixi.lock, pixi.toml, ponio/examples/belousov_zhabotinsky_pirock.cpp, ponio/examples/brusselator_advection_2d.cpp, ponio/examples/bz_2d_pirock.cpp, ponio/examples/heat_samurai.cpp, ponio/examples/nagumo_pirock.cpp, ponio/include/ponio/samurai_linear_algebra.hpp, ponio/test/test_samurai.hxx
Change samurai version: 0.19->0.25. Change `samurai_linear_algebra.hpp` to get a `samurai::VectorField` or `samurai::ScalarField`.
=> feat: change samurai version in examples
